{
    "token": '0nb8IPq9Py4USGFd7S7OU3paLUOueto-6TPE6hzLhFq5wOckI5-s_BtzoIseb9uNQ8iAUaCNLw5htbSBaMWP5Ho3POi5v2dSRY93boQhmRwSemT3vDZY7LUqlTmiA3SH',
    "study_id": '68a503bc8fdfadb762128e4d',
    "max_concurrent_sessions": 5,
    "workload_checker_period": 60
}